/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        apple: {
          red:          '#FF3B30',
          'red-dark':   '#C62222',
          'red-deep':   '#A01010',
          pink:         '#FF6B9D',
          'pink-light': '#FFE5F0',
          coral:        '#FF6B6B',
          rose:         '#FF2D55',
          gold:         '#FFD60A',
          'gold-dark':  '#B89200',
          green:        '#34C759',
          'green-dark': '#248A3D',
          leaf:         '#30B853',
          bg:           '#FFF5F5',
          'bg-warm':    '#FFF0EC',
          card:         '#FFFFFF',
          text:         '#2D1B1B',
          muted:        '#8B5B5B',
          light:        '#C4A0A0',
          border:       '#FFD6D6',
          'border-dark':'#FFB3B3',
        },
        // 後方互換
        brand: {
          DEFAULT: '#FF3B30',
          dark:    '#C62222',
          light:   '#FFE5F0',
        },
        duo: {
          green:        '#34C759',
          'green-dark': '#248A3D',
          'green-light':'#D7FFB8',
          yellow:       '#FFD60A',
          'yellow-dark':'#B89200',
          blue:         '#007AFF',
          'blue-dark':  '#0062CC',
          red:          '#FF3B30',
          'red-dark':   '#C62222',
          orange:       '#FF9F0A',
          'orange-dark':'#CC7A00',
          bg:           '#FFF5F5',
          border:       '#FFD6D6',
          text:         '#2D1B1B',
          muted:        '#8B5B5B',
          light:        '#C4A0A0',
        },
        gold:   '#FFD60A',
        silver: '#C0C0C0',
        bronze: '#CD7F32',
        stage: {
          dojo:    '#FF3B30',
          builder: '#007AFF',
          creator: '#BF5AF2',
        },
      },
      fontFamily: {
        sans: ['Nunito', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      backgroundImage: {
        'apple-gradient':   'linear-gradient(135deg, #FF3B30 0%, #FF6B9D 100%)',
        'apple-warm':       'linear-gradient(180deg, #FF3B30 0%, #FF6B6B 50%, #FFB347 100%)',
        'apple-hero':       'linear-gradient(160deg, #FF2D55 0%, #FF3B30 40%, #FF6B6B 100%)',
        'card-shine':       'linear-gradient(135deg, rgba(255,255,255,0.15) 0%, rgba(255,255,255,0) 100%)',
      },
      animation: {
        'bounce-in':   'bounceIn 0.5s cubic-bezier(0.68,-0.55,0.27,1.55)',
        'pop':         'pop 0.3s ease-out',
        'wiggle':      'wiggle 0.6s ease-in-out',
        'float':       'float 3s ease-in-out infinite',
        'heart-beat':  'heartBeat 1.5s ease-in-out infinite',
        'slide-up':    'slideUp 0.4s ease-out',
        'confetti':    'confetti 0.8s ease-out forwards',
        'pulse-slow':  'pulse 3s ease-in-out infinite',
        'bounce-slow': 'bounce 2s infinite',
        'spin-slow':   'spin 3s linear infinite',
        'shake':       'shake 0.5s ease-in-out',
      },
      keyframes: {
        bounceIn: {
          '0%':   { transform: 'scale(0.3)', opacity: '0' },
          '60%':  { transform: 'scale(1.15)' },
          '80%':  { transform: 'scale(0.95)' },
          '100%': { transform: 'scale(1)',   opacity: '1' },
        },
        pop: {
          '0%':   { transform: 'scale(1)' },
          '50%':  { transform: 'scale(1.25)' },
          '100%': { transform: 'scale(1)' },
        },
        wiggle: {
          '0%,100%': { transform: 'rotate(-8deg) scale(1.05)' },
          '50%':     { transform: 'rotate(8deg) scale(1.05)' },
        },
        float: {
          '0%,100%': { transform: 'translateY(0px) rotate(-2deg)' },
          '50%':     { transform: 'translateY(-12px) rotate(2deg)' },
        },
        heartBeat: {
          '0%,100%': { transform: 'scale(1)' },
          '14%':     { transform: 'scale(1.2)' },
          '28%':     { transform: 'scale(1)' },
          '42%':     { transform: 'scale(1.15)' },
          '70%':     { transform: 'scale(1)' },
        },
        slideUp: {
          '0%':   { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)',    opacity: '1' },
        },
        shake: {
          '0%,100%': { transform: 'translateX(0)' },
          '20%':     { transform: 'translateX(-6px)' },
          '40%':     { transform: 'translateX(6px)' },
          '60%':     { transform: 'translateX(-4px)' },
          '80%':     { transform: 'translateX(4px)' },
        },
      },
      boxShadow: {
        'apple':    '0 4px 0 0 #C62222',
        'apple-lg': '0 6px 0 0 #C62222',
        'apple-sm': '0 3px 0 0 #C62222',
        'pink':     '0 4px 0 0 #CC2255',
        'glow-red': '0 0 20px rgba(255,59,48,0.4)',
        'glow-gold':'0 0 20px rgba(255,214,10,0.5)',
        'card':     '0 2px 12px rgba(255,59,48,0.08)',
        'card-hover':'0 8px 24px rgba(255,59,48,0.16)',
      },
    },
  },
  plugins: [],
};
